spring:
  application:
    name: user-service
  datasource:
    url: jdbc:${CLEARDB_DATABASE_URL}
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
springdoc:
  swagger-ui:
    path: /swagger-ui.html
jwt:
  expiration: 640000000
  secret: WordToAddInTokenAccess
server:
  port: ${SERVER_PORT:8081}
aws:
  access_key_id: ${S3_ACCESS_KEY:}
  secret_access_key: ${S3_SECRET_ACCESS_KEY:}
  s3_bucket: s3-jornada
  region: us-east-1