spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:jornada-db}
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: 'true'
springdoc:
  swagger-ui:
    path: /swagger-ui.html
server:
  port: ${SERVER_PORT:8000}
