spring:
  application:
    name: user-service
  datasource:
# ---- H2 Database ----
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
    url: jdbc:h2:mem:testdb
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: 'true'
springdoc:
  swagger-ui:
    path: /swagger-ui.html
jwt:
  expiration: 640000000
  secret: WordToAddInTokenAccess
server:
  port: ${SERVER_PORT:8081}
aws:
  access_key_id: ${S3_ACCESS_KEY:}
  secret_access_key: ${S3_SECRET_ACCESS_KEY:}
  s3_bucket: jornada-back
  region: us-east-1